import type {GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { requireAuthentication } from "../HOC/requireAuthentication";
import styles from "../styles/Home.module.css";
import {Navbar} from "../components/Navbar";
import axios from "axios";
import {URL} from "../constants/url";
import {useState} from "react";
import {axiosJWT} from "../utils/axios/axios";
import {useRouter} from "next/router";
import {MainPage} from "../components/MainPage";
export type MainPageProps = {
    boards: {id: number, owner: number, name: string}[];
}
const Home: NextPage<MainPageProps> = ({boards}) => {
    console.log(boards)

  return (
    // <div className={styles.container}>
      <>
      <Head>
        <title>Страница заданий</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar isLogin={true} />
          <MainPage boards={boards}/>

    </>
    // </div>
  );
};

export default Home;
export const getServerSideProps: GetServerSideProps = requireAuthentication(
    async (ctx) => {
        // console.log(ctx.req.headers.cookie);
        // const res = await axios.get(`${URL}/todo/get/`, {withCredentials: true, headers: {
        //         Cookie: ctx.req.headers.cookie
        //     }});
        const res = await axios.get(`${URL}/board/get/`, {withCredentials: true, headers: {
                Cookie: ctx.req.headers.cookie
            }});
        const boards = await res.data;
        return {
            props: {boards},
        };
    }
);
